README.md, autoreact/__init__.py, autoreact/autoreact.py, autoreact/info.json
* **What issue is this related to (if applicable)?**  
Issue #47
* Commands
N/A
=> feat(autoreact): Added autoreact cog

README.md
* **What issue is this related to (if applicable)?**  
I just wanted my name on the list
* Add Issy to author list
N/A
=> docs(README.md): Add Issy to author list

.github/workflows/pythonapp.yml
Resolves #62 
* Changes pythonapp.yml's github action to trigger on PR
* N/A
N/A
=> ci(pythonapp): forked repos not being able to be merged

.github/workflows/pythonapp.yml, Dockerfile
Also ensure that no cache from APT or pip is in the docker image
Resolves #
* Makes docker images smaller
* improves building times since most it can be cached
* Adds breaking change which causes \<issue\>.
=> fix(Dockerfile): Combine RUN Statements to better use caching

README.md
N/A
* Tidies up README and re-orders the cog summaries list
* N/A
N/A
=> docs(readme): tidy up readme with ordering and removing duplicates

notes/notes.py
=> bug(notes): notes deletion

README.md, autoreply/__init__.py, autoreply/autoreply.py, autoreply/info.json
Resolves #75 
* The bot will autorespond to messages which match certain triggers
N/A
Command group is `autoreply`
Subcommands are as follows:
- `add` - Add an autoreply trigger. This uses no args
- `view` - View the autoreply configuration for the guild
- `remove`/`delete` Delete an autoreply trigger. This requires a number arg to be provided, which can be found using the `view` command
The trigger detection is case insensitive
=> docs(README.md): Added AutoReply to docs

verify/verify.py
Resolves #82 
* Adds welcome message to a designated channel
* String interpolation on verify message to allow a user mention with `{user}`
* Allows resetting of welcome message by calling `[p]verify welcome`
* N/A
* Tidied up verify cog code and removed redundant string interpolations
=> feat(verify): add welcome message

README.md
Resolves #84 
* Improved cog docs with base commands for each cog.
* Added missing cogs:
* Enforcer
* Notes
* Reactrole
* N/A.
N/A.
=> chore(readme): Improve cog docs.

enforcer/enforcer.py
Resolves #88
* Adds check for embeds list before creating a menu
* N/A
N/A
=> fix(enforcer): add length check

report/report.py
Resolves #41
* Adds human readable timestamp to report embed
* N/A
N/A
=> feat(report): add readable timestamp to report cog

README.md, penis/__init__.py, penis/info.json, penis/penis.py
N/A
* Adds the existing penis cog with a change to make the invoker the default when no user is specified
=> feat(penis): Add penis command

autoreact/autoreact.py, report/report.py
Resolves #54 
Resolves #41 
* Adds emergency command. Just like report command, but pings all active mods
* Causes merge conflict with (currently unmerged) PR #87 
This also incorporates the changes from (currently unmerged) PR #87, so #87 should not be merged if this PR is to be merged
(I also removed some trailing whitespace from the autoreact cog lol)
=> feat(report): add emergency command

README.md, xkcd/__init__.py, xkcd/info.json, xkcd/xkcd.py
Resolves 
* Adds xkcd command which gets specified comic or latest comic if none is specified
* N/A
=> Add xkcd command

verify/verify.py
Resolves #100
* Enables blocking and unblocking of verification for users
* Adds blocked users count to status
* New commands to block and unblock
* N/A
N/A
=> feat(verify): add block and unblock commands for verification

README.md, convert/__init__.py, convert/convert.py, convert/info.json
None.
* Adds cog convert which will convert any unit to an another unit.
None.
None.
=> Add cog convert

autoreact/autoreact.py
Resolves the issue of mods not being able to change settings related to this cog
N/A
N/A
N/A
=> fix(autoreact): Change permission level from admin to mod

.github/pull_request_template.md
N/A
* Added myself to list of suggested reviewers
N/A
N/A
=> docs(PR template): Added myself to PR template

README.md
No.
* Re-style contributors list in readme.me
=> docs(readme): Re-style contributors list.

report/report.py
Resolves #90 
* Adds feature to notify users via DM when reports (including emergencies) are filed.
* No known breaking changes.
=> DM report/emergency confirmation.

README.md
N/A
* Adds some better documentation for a few cogs
* N/A
N/A
=> docs(readme): add info about enforcer, notes, purge & reports

enforcer/enforcer.py, reactrole/reactrole.py
Resolves #120
* Fixes errors in the enforcer status command and the reactrole list command by checking against len(list(generator)) instead of len(generator)
N/A
=> Fix pagify issue in #120

README.md
No.
* Various minor fixes to readme.md including spelling, grammar, a broken link, and so on.
=> docs(readme): Spelling, broken link, etc.

latex/__init__.py
Resolves #127 
* None
* Shouldn't break anything.
Fix the issue causing the cog to error out upon loading.
=> Fix #127 - cog failing to load due to too many parameters.

README.md, report/report.py
Resolves #124
* Adds commands to toggle the report/emergency commands in specific channels
- `[p]emergencies channel <allow|deny> <channel>`
- `[p]reports channel <allow|deny> <channel>`
* Changed embed format to render timestamps clientside (to account for timezones other than UTC+0)
* I hope not
N/A
=> #124 Report channel blocklist

README.md, verify/verify.py
Resolves #133
* None, just docs improvements.
* None, probably 👀
=> docs(verify): Documentation improvements.

info.json
N/A.
* Add info.json for repository as per https://docs.discord.red/en/stable/guide_publish_cogs.html#info-json-format
* None.
=> feat(info.json): Add info.json for repo

google/google.py
Please, no one try it.
* Adds feature which can either prevent or accelerate breakage of internet.
=> With all due respect, I am head of IT.

README.md
I forgot to add the roleinfo to the docs index. That's all
=> docs(readme): Added roleinfo to readme index

README.md
Fixes the broken links in the README
- Pointed the links to GitHub instead of GitLab at the bottom of the readme
=> fix(readme): Fix links in readme

.github/scripts/json_checker.py, autoreact/autoreact.py, autoreply/autoreply.py, convert/convert.py, enforcer/enforcer.py, feed/feed.py, latex/latex.py, notes/notes.py, purge/purge.py, quotes/quotes.py, reactrole/reactrole.py, report/report.py, roleinfo/roleinfo.py, verify/verify.py, xkcd/xkcd.py
This is just a collection of fixes to reduce code bloat and create a unified naming convention
- Unifies most embed colours to match config set colour
- Code style changes
It passes the linter checks so uhhhh probably not?
=> General refactoring

enforcer/enforcer.py, enforcer/info.json
Resolves #129
* Enforcer now messages users about enforced message
* Enforced channel now included in log message
* Enforcer now recognises embeds as media
* Enforcer now correctly evaluates the guild age of a member
* Enforcer now correctly numbers pages in `[p]enforcer status`
N/A
=> Enforcer improvements

.github/scripts/json_checker.py, .github/workflows/ci.yml, .gitignore, verify/info.json, verify/verify.py
* Resolves #33
* Resolves #123
* Resolves #146
* Resolves #147
* Added `fuzziness` setting to verify cog, which allows for non-strict verification checking
* Moved to event-based verification welcoming, so this cog will still work with a react-based verification system (à la reactrole)
* Sped up json checker CI workflow
* Updated all workflows to actions/setup-python@v2
* Extended .gitignore file with entries for Python, Pycharm, Sublime, Jupyter and VSCode
N/A
=> Verify & CI changes

info.json
=> fix(info.json): Fix typo in repo's info.json

report/report.py
Stops the report/emergency commands from throwing an error
=> fix(report): Hotfix - pre report check

README.md, notes/info.json, notes/notes.py
Resolves #66
Resolves #156
* Allows you to see notes of users not currently in the server
* Adds the edit subcommand for notes and warnings
* Adds the restore subcommand for deleted notes and warnings
* No breaking changes
=> Notes enhancements

README.md, letters/__init__.py, letters/info.json, letters/letters.py
N/A.
* Add `letters` cog. See readme for cog information.
N/A.
N/A.
=> feat(letters): Add letters cog

README.md, letters/letters.py
Resolves #160
* Add limited support for special characters (!?#'.,).
* Add `-raw` flag to output emote code in code block.
* Limit output length to 2000 characters.
N/A.
N/A.
=> feat(letters): Various enhancements

README.md, sentry/__init__.py, sentry/info.json, sentry/sentry.py
Resolves #
* Adds error reporting to sentry
=> Sentry cog

README.md, sentry/sentry.py
=> Sentry updates

sentry/sentry.py
Fix environment being loaded for guild which both I and @issy missed in review
* Add more tags
=> Sentry updates electric boogaloo

sentry/sentry.py
Fix Sentry killing the bot, whops
=> sentry: fix optional variables not checked for existence

sentry/sentry.py
Resolves a critical issue with Sentry which results in an unresponsive bot.
* N/A.
* N/A.
* N/A.
=> Fix breaking Sentry bug

sentry/sentry.py
N/A.
* Send message before raising test exception so the user is aware the cog has successfully failed.
* N/A.
N/A.
=> feat(sentry): Clarify test functionality

README.md, enforcer/enforcer.py
No.
* Adds `maxchars` attribute to the enforcer cog.
* None.
I'm not confident that this is correct, hence opening as a draft. Please let me know what you think @issy.
=> feat(enforcer): Add maxchars attribute

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/cog-enhancement.md, .github/ISSUE_TEMPLATE/new-bot-cog.md, .github/pull_request_template.md
N/A
* Adds checkboxes to PR and issue templates
N/A
N/A
=> docs(templates): Changed bullet points to checkboxes

reactrole/reactrole.py
Resolves #179
* Clears the target reaction in `[p]reactrole remove`
* Optimises some of the config logic in reactrole, in accordance with code in other cogs
* Added typehints to functions in reactrole
N/A
N/A
=> Reactrole refactor

README.md, sentry/sentry.py
Resolves #
* Adds feature/fix which does xyz.
* Adds breaking change which causes \<issue\>.
=> add sentry logging and better error handling

xkcd/xkcd.py
Resolves # https://discord.com/channels/184315303323238400/351996726728720387/919849600146358293
* Makes title of xkcd embed a clickable link to the comic
* Might break some peoples brains idk
=> Make xkcd title a clickable link

sentry/sentry.py
Sentry cog not working.
* Sentry cog working (#189).
* N/A.
N/A.
=> Bring master inline with develop

notes/__init__.py, notes/abstracts.py, notes/info.json, notes/notes.py, notes/utils.py
* Fixes an issue where you couldn't list all notes for a guild with `[p]notes list`
* Adds `[p](notes|warnings) restore <id>` commands
* Refactor of the entire cog
* Cleaned up a lot of the logic
* Separated the config section of the code for operational clarity
N/A
N/A
=> Notes cog refactor

README.md, custom_msg/__init__.py, custom_msg/custom_msg.py, custom_msg/info.json, custom_msg/interactive_session.py, notes/__init__.py, notes/abstracts.py, notes/info.json, notes/notes.py, notes/utils.py
Resolves #181
* Adds new custom-msg cog
* Refactor of notes cog to allow listing all notes in a guild
N/A
=> Bring master up to date with develop

xkcd/xkcd.py
Reverts rHomelab/LabBot-Cogs#187
not actually a feature discord supports in embed titles.
=> Revert "Make xkcd title a clickable link"

notes/abstracts.py, notes/utils.py
Resolves an issue with `[p]notes list` command
- Sets the correct field type when retrieving and creating notes
=> [FIX] Correct field typing in notes cog

penis/penis.py
N/A.
* Append "lol small" to output if penis length <= 6.
* Probably none :)
N/A.
=> feat(penis): append 'lol small' if len <= 6

README.md, phishingdetection/__init__.py, phishingdetection/info.json, phishingdetection/phishingdetection.py
N/A
* Adds cog that deletes links to scam websites
N/A
This cog fetches a list of scam links from an API, and then uses that to check all incoming messages for those links. If it finds any of those links in the message, it deletes the message.
It fetches updates to the list every hour. In the future it would be nice to have the bot timeout/report the offending user, especially if they post multiple known links in a short timespan.
=> Detect scam links and delete them

README.md, notes/abstracts.py, notes/utils.py, phishingdetection/__init__.py, phishingdetection/info.json, phishingdetection/phishingdetection.py
N/A.
* penis cog: append 'lol small' if penis length <= 6 [#199]
* create phishingdetection cog [#198]
* None 🤞
N/A.
=> Bring master inline with develop.

purge/purge.py
No.
* Adds timestamp and user ID to embed report.
* None.
N/A.
=> feat(purge): add timestamp and user ID to embed

README.md, timeout/__init__.py, timeout/info.json, timeout/notice.txt, timeout/timeout.py
This is a step towards #10, but is far from fulfilling even the basic DoD's.  
In short, no.
* Adds a cog to add/remove users from timeout.
* None.
This is the first cog towards which I've made any sort of significant contribution, and is my first time working with a lot of the things I've done here.
I've already identified a few areas for improvement which I plan to address in the future, but, at least in my mind, this is a MVP which works as we need for now.
One such area for improvement is using Red's built-in `MessagePredicate` here to avoid this messy logic:
https://github.com/rHomelab/LabBot-Cogs/blob/f379d2e3111ea17b171a707dcf6339acaccf8136/timeout/timeout.py#L157-L164
That said, any//all feedback would be much appreciated, not matter how nitpicky!
=> Add timeout cog

.github/pull_request_template.md, README.md
Required before removal of develop branch.
=> Replace references to develop branch with "master"

.github/pull_request_template.md, README.md
No
* Updates branch references after renaming master to main.
* N/A.
N/A.
=> chore: replace references to master branch with main

sentry/sentry.py
No
* Set logger name per Red's recommendations.
* Catch invalid log level specified by user.
* Return useful response for `get_env` when env is unset.
* Restyle get/set command responses.
* N/A
N/A
=> sentry: refactor logging, improve error handling and responses

README.md, timeout/timeout.py
Resolves #216
* Fixes #216 by adding logic to handle boosted members
* Add logging
* Add `[p]timeoutset list` command aliases.
* Adds breaking change which causes \<issue\>.
I'm bored of this template and will probably simplify it a ton at some point. Thanks for coming to my TED Talk.
=> timeout: fix boosted member handling, add logging

timeout/timeout.py
Resolves #225
* Fix a TypeError exception caused by trying to reference a set as a set of sets.
* Resolve lint warnings and an erroneous return on exception.
* plsno.
N/A.
=> Fix: timeout cog exception

README.md, tags/__init__.py, tags/info.json, tags/tags.py
Resolves #177 
* Implements the tags feature as specified in the above issue. 
* Nothing should break.
All DoD features are complete. Features to be added yet:
* Logging that respects the config options.
* Ability to configure logging with commands.
* Searching (not quite sure what @issy had in mind for this).
* Stats and info (also not entirely sure what @issy wanted for either of these). Re: stats: Every use of tags and aliases and transfer of tag ownership is logged, so there should be plenty of statistics we can pull once that's sorted.
=> feat/177 Tags Cog

autoreact/autoreact.py
Resolves #232
* Catches exception and outputs a log message if a message is not found when attempting to add a reaction.
* None
=> fix/autoreact: catch and log exception if message not found

tags/tags.py
Resolves #237 
* Adds docstrings for the help menu.
* No breaking changes.
N/A
=> Resolves #237 by adding docstrings for the help menu.

markov/markov.py
Reverts https://github.com/rHomelab/LabBot-Cogs/commit/8f1e98a9e7f6e9b382a45081908b945c33f337ee
This breaks migrations from the previous markov cog as the data is saved with the unique ID. Upgrading also requires all the users to opt in again
* Adds feature/fix which does xyz.
* Adds breaking change which causes \<issue\>.
=> Revert markov unique ID change

README.md, topic/__init__.py, topic/info.json, topic/topic.py
* No but it does resolve a #feedback request
* Adds topic command as requested by https://discord.com/channels/184315303323238400/351996726728720387/1149066321485643937
* There shouldn't be but we all know how reliable my code is.
N/A
=> feat/topic: Add new topic command cog per #feedback suggestion.

README.md, betterping/__init__.py, betterping/betterping.py, betterping/info.json
Nah
* Adds a new cog, BetterPing, to replace the built-in ping command.
* N/A
=> BetterPing: add new cog

notes/abstracts.py, notes/notes.py, notes/utils.py
Resolves #235 
* Responds with note ID when adding a note or warning.
* Shouldn't be any.
n/a
=> Reply with note/warning note ID as requested in #235.

notes/abstracts.py, notes/utils.py
N/A.
* Sort notes & warnings in `[p]notes list` by date, without bucketing by type.
N/A.
N/A.
=> notes: sort notes/warns by date

README.md, tags/abstracts.py, tags/tags.py, tags/utils.py
Resolves #238 
* Nearly complete rewrite to add config wrapping.
* Adds a (very) basic listing feature with optional user filter.
* Adds tag info command with basic statistics and brief history.
* Legacy configs **will** break the cog. A config converter is available (contact me for details). Unload then uninstall the cog, shutdown the bot (yes, from my testing, this is needed), replace the config file with the updated config, then start the bot, install, and load the cog.
Sorry for all the commits. This was an adventure.
=> Feat/238 Additional Tags Features

prometheus_exporter/main.py, prometheus_exporter/prom_server.py, prometheus_exporter/stats.py, prometheus_exporter/utils.py
* Adds prom cog logging
* sets poll interval config as int instead of float
=> adding logging to the prom cog for easier debugging

isitreadonlyfriday/isitreadonlyfriday.py
Not logged.
* Fixes a missing character because I'm dumb 👍
=> fix(isitreadonlyfriday): add a missing character

tags/tags.py
Resolves #281 
* Returns list of tags and aliases as separate, pagified menus.
* Markdown in tag and alias names is escaped. I was going to implement `redbot.core.utils.chat_formatting.escape`, but it appears to be done for me as a result of throwing the output into pagified menus.
hope not :)  
I kid, I did some basic testing and it seems fine™️
=> fix(tags): escape markdown, pagify output

README.md, isitreadonlyfriday/isitreadonlyfriday.py
Resolves #289 
* Adds the ability to check if it's read-only December.
* None known. 
N/A
=> Resolves #289: Read-Only December

latex/latex.py
Resolves #294 
* Fixes LaTeX statement rendering
* None
None
=> Resolves #294 to properly render LaTeX statements.

role_welcome/role_welcome.py
Not logged, but yes:
* Fixes `[p]rolewelcome message <multi-word string>` not being correctly captured.
=> fix(role_welcome): capture full welcome message input

README.md, role_welcome/role_welcome.py
No
* Adds `backfill_welcomed_users` command to `role_welcome` cog.
=> feat(role_welcome): add `backfill_welcomed_users` command

penis/penis.py
added big dong appreciation
* Adds a msg for having a large dong
added constance to comply to ci when #264 is merged
=> feat(penis): added dong constants

notes/notes.py, notes/utils.py
* correct string formatting in Note class
=> fix: correct string formatting in Note class

requirements-dev.txt, requirements.txt
* chore: move `prometheus-client` to dev requirements
* chore: add missing `chat_exporter` dev requirement
=> chore: update requirements

README.md, onboarding_role/__init__.py, onboarding_role/info.json, onboarding_role/onboarding_role.py
Resolves #284
* Adds `onboarding_role` cog.
=> Add `onboarding_role` cog

README.md, guild_profiles/__init__.py, guild_profiles/guild_profiles.py, guild_profiles/info.json, requirements-dev.txt
Thought I created one for this but nope 🤷 
* Adds `guild_profiles` cog.
N/A.
This was mostly written by an LLM because I couldn't be bothered. It works though ¯\\\_(ツ)_/¯
=> feat: add `guild_profiles` cog

timeout/timeout.py
Resolves #322 - users should be disconnected from voice when timed out
* Adds feature of removing users from voice chat, if they are connected, While being timed out
=> Feat timeout voice
