rHomelab/LabBot-Cogs

- feed/feed.py
Stops the bot from erroring out when a member has no nickname
> fix(feed.py): Use member.display_name

- report/report.py
Resolves #55
* Allows message to be null so `[p]report` will not give command instructions in the case of no message provided
* N/A
N/A
> fix(report): add nullable message to report command

- quotes/quotes.py
N/A
* If someone doesn't provide any message IDs in the quote command, the bot will let them know instead of failing silently
N/A
N/A
> fix(quotes.py): Added error checking for quote command

- .flake8
- .github/workflows/ci.yml
- .vscode/tasks.json
- README.md
- pyproject.toml
Completes part of #144 
* Adds VSCode tasks which mimic the CI workflows
* Adds Flake8 config so it doesn't clash with Black on certain things
To run the tasks locally just open the repo in VSCode, open the command palette and type in `run task`. This will give you a list of the available tasks you can run. Most of these tasks also have problem matchers, so if it detects issues with the code it will flag the exact line and column in the `problems` tab of VSCode
> Add VSCode tasks

- letters/info.json
- letters/letters.py
Fixes some buggy behaviour in the letters command regarding punctuation.
**Before** `....` => `:. :.`
**Now** `....` => `....`
* Fixes the punctuation spacing/substitution in the letters command
* Moved the bulk of the letters functionality to command arg converters
* N/A
I wanted to utilise the `commands.clean_content` converter to aid with cleaning up user/role/channel mentions, but the current version of the provided converter does not implement the expected functionality properly. In discord.py 2.0 it is fixed, so when that's released we can resolve that.
> [FIX] Punctuation spacing/substitution in letters command

- notes/utils.py
Resolves an issue with the `[p]notes list` command where it would crash if there were stored notes that had been added while the note target user was not in the guild.
This stems from an issue in the [original notes cog](https://github.com/rHomelab/LabBot-Cogs/commit/520400695ccd7a91b7cdd828cb32edd5e5025417#diff-8268e6909724c46561b0b0417d6f74552c4045377e4578746f023793ac5d7bd5R53) (pre refactor) where if a note was added by user ID for a user not in the guild, the `member_id` field would be stored as a string instead of an integer. In the refactor, note data is typechecked, so this failed the typechecking every time notes were retrieved from config.
* Fixes `[p]notes list` command
* N/A
In the future I will implement a data migration task to change all …
> Fix `[p]notes list` command

- notes/abstracts.py
- notes/utils.py
Resolves an issue with the `[p]notes list` command
- Sets the correct field type when retrieving and creating notes
> fix(notes): Cast created_at to int (#196)

- phishingdetection/phishingdetection.py
Matches URLs properly, instead of allowing for overmatching (twitch.tv was matching because of a URL called witch.tv in the banlist)
Here is an example of the new pattern in action
> Fortify URL matching in phishing detection cog

- reactrole/reactrole.py
fix(reactrole): reaction should be str from start instead of casted later
No
* There's a bug where reactrole isn't able to use a unicode emoji when it's type hinted as discord.Emoji or PartialEmoji.  Since it's casted as str later on anyways before submitting to the API, I just made it a str from the start which solved the problem I was running into.
N/A
> fix(reactrole): reaction should be str from start instead of casted later

- pyproject.toml
Removes useless PyLint options:
* R0201 (`no-self-use`) was removed in PyCQA/pylint/pull/6448
* C0330 (`bad-continuation`) was removed in PyCQA/pylint/pull/3571
* C0326 (`bad-whitespace`) was removed in PyCQA/pylint/pull/3577
> chore(pylint): remove useless option values

- README.md
- verify/info.json
- verify/verify.py
Yes, but I didn't log it. Whoops.
The verify cog's welcome message functionality works as expected, but causes issues with the timeout cog. Since the timeout cog strips all roles while the user is in timeout, when the user is removed from timeout and the roles are restored, the verify cog thinks they're a new member and welcomes them accordingly.
* Adds `welcomeignore` option to verify. Do not welcome a member when their former roles included a role added to welcomeignore.
* None, I hope :)
> verify: Add welcomeignore setting, don't welcome when role in previous roles

- enforcer/enforcer.py
- report/report.py
- timeout/timeout.py
- verify/verify.py
Resolves #224
* Replaces `Member.avatar_url` ([removed in discord.py v2](https://discordpy.readthedocs.io/en/latest/migrating.html#asset-redesign-and-changes)) with `Member.display_avatar.url`.
* Bloody well hope not.
Thanks @portalBlock :heart:
> Fix: use Member.display_avatar.url instead of Member.avatar_url

- enforcer/enforcer.py
- verify/verify.py
Resolves #229
* replace `datetime.utcnow()` with `discord.utils.utcnow()`
See [`datetime` Objects Are Now UTC-Aware](https://discordpy.readthedocs.io/en/latest/migrating.html#datetime-objects-are-now-utc-aware)
* hope not !
Hopefully this is the last of it.
> discordpy v2 migrations

- feed/__init__.py
- feed/feed.py
nah
* Feed will now be available from the user and message context menus and will mention the user being fed.
hope not
> feat/feed: add context menu commands

- README.md
- prom_export/__init__.py
- prom_export/info.json
- prom_export/main.py
- prom_export/prom_server.py
- prom_export/stats.py
- requirements.txt
no :(
* Adds a prometheus exporter for red
* N/A
N/A
> added a new prom exporter cog

- .vscode/extensions.json
- .vscode/settings.json
No
* Removes deprecated VSCode setting
N/A
All settings starting with "python.linting." are deprecated and can be removed from settings. https://code.visualstudio.com/docs/python/linting
https://code.visualstudio.com/docs/python/linting
> chore: remove deprecated VSCode setting

- bancount/bancount.py
N/A.
* Removes the default limit of 1000 on `Guild.bans`
* Catches missing permissions when attempting to retrieve bans
* Uses `typing()` to send a typing indicator while ban list is being retrieved.
N/A.
N/A.
> bancount: remove limitation on number of bans retrieved and catch missing permissions

- custom_msg/custom_msg.py
No
* Makes the custom_msg cog return a clickable message link instead of `<channel_id>-<msg_id>`.
N/A
N/A
> feat(custom_msg): return link to sent message

- prometheus_exporter/main.py
- prometheus_exporter/prom_server.py
- prometheus_exporter/stats.py
- prometheus_exporter/utils.py
Not logged in issues but yes - @rippleFCL's decision to log every single member and force the log level to debug resulted in never-ending log spam.
* Fixes enforced `DEBUG` log level.
* Fixes the existence of an unnecessary log statement.
* Re-adds the activity metrics addition statement, erroneously removed in d28819d.
> fix prometheus_exporter logging, isort, activity metrics addition

- report/report.py
Resolves #272 
* Removes dependency on the deprecated `distutils` package.
See PEP 632 for context.
I feel there may be a better/more recommended way to handle the way this function is used in the cog, but this is a quick and simple fix.
> fix(report): reimplement strtobool to eliminate distutils dependency

- xkcd/xkcd.py
Resolves #274
* Fixes missing alt text even when present for requested comic.
> fix(xkcd): invert boolean logic for alt text presence

- isitreadonlyfriday/isitreadonlyfriday.py
nop
* Improves docstrings / command help messages.
* Validate offset is within range before making request.
> isitreadonlyfriday: docs and input validation

- README.md
Replace manually maintained list of contributors with notice of gratitude and link to GitHub's list of repo contributors.
> docs: replace manual list of contributors

- README.md
- role_welcome/__init__.py
- role_welcome/info.json
- role_welcome/role_welcome.py
**TL;DR:** This cog welcomes users who are new to a defined role. Mods can set a trigger role, templated welcome message, welcome channel, and more (see readme).
Not logged, but yes. Cba writing a reasonable explanation so here's my 3 AM ramblings:
> ok so one thing I need to do before actually making this [jail cog] usable is to tweak our verify cog
> Or, tbh, just strip out the one, tiny part of it that we still actually use and make it its own cog lol
> The verify cog does a ton of cool stuff that we just don't use anymore, it's from back when we had a far more customised and involved user join process
> All we use it for these days is join messages ("Welcome, user!"), triggered by someone having a defined role (Labbers role) applied
> The problem there …
> feat(role_welcome): new cog

- enforcer/enforcer.py
- markov/markov.py
- quotes/quotes.py
- reactrole/reactrole.py
- report/report.py
- timeout/timeout.py
- verify/verify.py
Hotfix for `AttributeError` exception in several cogs due to bad type reference introduced in #264:
```
def _is_valid_channel(self, channel: discord.guild.GuildChannel | None):
^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord.guild' has no attribute 'GuildChannel'
```
This re-introduces some type errors, but is required to fix cog failures for the time being.
> fix: hotfix for bad `GuildChannel` type reference

- quotes/quotes.py
- topic/topic.py
Hotfix for `AttributeError` exception in several cogs due to bad type reference introduced in #264:
```
def _is_valid_channel(self, channel: discord.abc.MessageableChannel | discord.interactions.InteractionChannel | None):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord.abc' has no attribute 'MessageableChannel'
```
This re-introduces some type errors, but is required to fix cog failures for the time being.
> fix: hotfix for bad `MessageableChannel` type reference

- enforcer/enforcer.py
- markov/markov.py
- quotes/quotes.py
- reactrole/reactrole.py
- report/report.py
- timeout/timeout.py
- topic/topic.py
- verify/verify.py
Resolves #304 
#302 and #303 switched to runtime available types for a hotfix. These are incorrect.
This change switches back to the original correct types but quotes them so it doesn't cause runtime issues.
> fix: restore types and quote them instead

- README.md
- report/report.py
Resolves #282
Resolves #42 
* Implements slash commands for `report` and `emergency`.
* Adds link to message before report in report embed.
* Adds `[p]reports status` command.
* Adds 1/30s cooldown for `report` and `emergency` commands (text-based and slash).
* DM bot owner(s) when a report is made without a configured log channel.
* Removes `enabled_channels` functionality. The same can be achieved with Red's [`permissions`](https://docs.discord.red/en/stable/cog_guides/permissions.html) functionality.
* The `[p]reports confirm` command is now `[p]reports confirmation`.
* The `[p]reports logchannel` and `[p]reports confirmation` commands can only be run from within a guild.
> Improve `report` cog

- notes/notes.py
- notes/utils.py
Resolves issue where markdown control characters were not escaped in output of `[p]notes list`.
* Escapes markdown formatting in output of `[p]notes list`.
> fix(notes): escape markdown in usernames

- .github/actions/check-json/json_checker.py
Fixes bug seen in #312 where a key with regex control characters (`$schema` in this case) breaks the matching and results in a raw, unhandled exception.
> fix(check-json): escape regex controls in JSON keys

- custom_msg/interactive_session.py
Resolves issue where messages longer than 2000 characters result in an uncaught exception.
* `custom_msg` catches messages >2000 characters and asks the user to retry.
> fix(custom_msg): catch messages >2000 characters

- README.md
- onboarding_role/onboarding_role.py
No
* Adds `[p]onboarding_role process` command.
* Fixes typos.
* Add single quotes to guild, channel, role, and member names in log messages.
> onboarding_role: add `process` command

- README.md
- report/report.py
Yes (not logged) 🥲 Commit 7ed73e09aa781a4fa6433a97ec5a360484f0946b was a big dumb on my part and has resulted in the emergency command being broken in almost all cases since then.
* Fixes broken emergency reports.
* Adds `maxmentions` setting to limit how many members of the log channel can be mentioned (default: 20).
* Adds character limit checks & handling.
* Batch large numbers of user mentions across multiple messages
* Truncate user reports, notifying them via interaction response or DM when this occurs.
* Improve logging and handling of other edge cases/potential errors.
* Always return report confirmations to interactions.
* Fixes some typos.
Hopefully none :)
> Fix emergency reports

- guild_profiles/guild_profiles.py
- jail/jail.py
- notes/utils.py
- purge/purge.py
- quotes/quotes.py
- report/report.py
- roleinfo/roleinfo.py
- tags/tags.py
- tags/utils.py
- timeout/timeout.py
No
* Use timezone-aware datetime objects (mostly via substitution of `datetime.datetime.now()` with `discord.utils.utcnow()`)
* Use `discord.utils.format_dt()` to format datetimes for Discord instead of manually constructing strings.
> refactor: datetime handling improvements

- create_dev_bot.sh
- renovate.json
No
* Adds Renovate custom manager and package rule to patch cog requirements.
* Adds Renovate package rule to ignore `requirements.txt` — This file is managed by a CI workflow which compiles all cog deps into one file.
* Fixes `create_dev_bot.sh` by installing dev requirements (`requirements-dev.txt`).
> chore(renovate): add manager for cog deps

- renovate.json
Not logged
* Reverts part of #350 - This allows Renovate to patch both files at once (cog `info.json` & `requirements.txt`), which avoids the `compile-requirements` workflow modifying the PR and making Renovate unhappy.
> chore(renovate): don't ignore requirements.txt
